version: '3.8'

services:
  monster:
    image: amouat/dnmonster
    ports:
      - 8080:8080

  fastapi:
    build: ../backend
    ports:
      - 8000:8000
    depends_on:
      - monster
    volumes:
      - ../images/:/images

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi

